# This is a basic workflow to help you get started with Actions

name: Build, Pack, Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push but only for the master branch
  pull_request:
    types: [ closed ]
    tags:
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-create-draft:
    # Only run if it was a PR merge
    if: github.event.pull_request.merged == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          echo ${GITHUB_REF#refs/tags/v} > tag.txt
          echo "::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/v}"
      - name: Upload version
        uses: actions/upload-artifact@v2
        with:
          name: tag
          path: tag.txt

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Jar
        run: ./gradlew shadowJar
      # Upload this built jar
      - name: Upload final jar
        uses: actions/upload-artifact@v2
        with:
          name: fat-jar
          path: ./build/libs/FutureRestore GUI-1.0-all.jar

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: CoocooFroggy
          body-includes: FutureRestore GUI — v${{ steps.get_version.outputs.SOURCE_TAG }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.SOURCE_TAG }}
          release_name: FutureRestore GUI — v${{ steps.branch_name.outputs.SOURCE_TAG }}
          body: ${{ steps.find-comment.outputs.comment-body }}
          draft: true
          prerelease: true

      - name: Create upload URL file
        env:
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
        run: echo $UPLOAD_URL > upload-url.txt
      - name: Upload release's upload URL
        uses: actions/upload-artifact@v2
        with:
          name: upload-url
          path: upload-url.txt

      - name: Create release ID file
        env:
          RELEASE_ID: ${{ steps.create_release.outputs.id }}
        run: echo $RELEASE_ID > release-id.txt
      - name: Upload release's upload URL
        uses: actions/upload-artifact@v2
        with:
          name: release-id
          path: release-id.txt

  ubuntu-pack:
    needs: [ build-and-create-draft ]
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Download final jar
        uses: actions/download-artifact@v2
        with:
          name: fat-jar
          path: ./input

      - name: Download version
        uses: actions/download-artifact@v2
        with:
          name: tag
      - name: Output version
        id: output-version
        run: |
          version=$(tail tag.txt)
          echo "::set-output name=version::$version"

      - name: Run JPackage
        env:
          RUN_NUMBER: ${{ github.run_number }}
          VERSION: ${{ steps.output-version.outputs.version }}
        run: jpackage --input ./input --name "FutureRestore GUI" --main-jar "FutureRestore GUI-1.0-all.jar" --main-class Main --type deb --icon ./.github/workflows/ubuntu/Icon-1024.png --copyright "© CoocooFroggy 2021" --verbose --name "FutureRestore GUI" --module-path ./.github/workflows/ubuntu/javafx-jmods-11.0.2 --add-modules javafx.swing,javafx.graphics,javafx.base,java.logging,java.sql,java.base,jdk.crypto.ec,java.naming --app-version $VERSION 2>&1 | tee /tmp/jpackoutput.txt
      - name: Grep DEB name
        id: grep_deb_name
        run: |
          deb_name=$(grep -Po '(?<=Package \(.deb\) saved to: ).*(?=.)' /tmp/jpackoutput.txt)
          echo "::set-output name=deb_filename::$deb_name"

      - name: Download URL to upload to
        uses: actions/download-artifact@v2
        with:
          name: upload-url
        # Make it usable in Github actions
        # Make it usable in Github actions
      - name: Set output for upload-url
        id: set_upload_url
        run: |
          upload_url=$(tail upload-url.txt)
          echo "::set-output name=upload-url::$upload_url"

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.set_upload_url.outputs.upload-url }}
          asset_path: ${{ steps.grep_deb_name.outputs.deb_filename }}
          asset_name: FutureRestore-GUI-Debian-Continuous.deb
          asset_content_type: application/octet-stream



  macos-pack:
    needs: [ build-and-create-draft ]
    runs-on: macos-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Download final jar
        uses: actions/download-artifact@v2
        with:
          name: fat-jar
          path: ./input

      - name: Download version
        uses: actions/download-artifact@v2
        with:
          name: tag
      - name: Output version
        id: output-version
        run: |
          version=$(tail tag.txt)
          echo "::set-output name=version::$version"

      - name: Run JPackage and remove signature
        env:
          RUN_NUMBER: ${{ github.run_number}}
          VERSION: ${{ steps.output-version.outputs.version }}
        run: |
          jpackage --input ./input --main-jar "FutureRestore GUI-1.0-all.jar" --main-class Main --type app-image --icon ./.github/workflows/mac/FutureRestoreGUIIcons.icns --copyright "© CoocooFroggy 2021" --verbose --mac-package-identifier com.coocoofroggy.futurerestoregui --name "FutureRestore GUI" --module-path ./.github/workflows/mac/javafx-jmods-11.0.2 --add-modules javafx.swing,javafx.graphics,javafx.base,java.logging,java.sql,java.base,jdk.crypto.ec,java.naming --app-version $VERSION
          codesign --remove-signature FutureRestore\ GUI.app

      - name: Zip .app
        id: zip_app
        run: zip -r FutureRestore-GUI-Mac.zip "FutureRestore GUI.app"

      - name: Download URL to upload to
        uses: actions/download-artifact@v2
        with:
          name: upload-url
        # Make it usable in Github actions
      - name: Set output for upload-url
        id: set_upload_url
        run: |
          upload_url=$(tail upload-url.txt)
          echo "::set-output name=upload-url::$upload_url"

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.set_upload_url.outputs.upload-url }}
          asset_path: FutureRestore-GUI-Mac.zip
          asset_name: FutureRestore-GUI-Mac-Continuous.zip
          asset_content_type: application/zip

  windows-pack:
    needs: [ build-and-create-draft ]
    runs-on: windows-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Download final jar
        uses: actions/download-artifact@v2
        with:
          name: fat-jar
          path: ./input

      - name: Download version
        uses: actions/download-artifact@v2
        with:
          name: tag
      - name: Output version
        id: output-version
        run: |
          version=$(tail tag.txt)
          echo ::set-output name=version::$version
        shell: cmd

      - name: Run JPackage
        env:
          RUN_NUMBER: ${{ github.run_number}}
          VERSION: ${{ steps.output-version.outputs.version }}
        run: jpackage --input ./input --name "FutureRestore GUI" --main-jar "FutureRestore GUI-1.0-all.jar" --main-class Main --type msi --icon ./.github/workflows/windows/FRWindows.ico --copyright "© CoocooFroggy 2021" --verbose --name "FutureRestore GUI" --win-shortcut --win-menu --module-path ./.github/workflows/windows/javafx-jmods-11.0.2 --add-modules javafx.swing,javafx.graphics,javafx.base,java.logging,java.sql,java.base,jdk.crypto.ec,java.naming --app-version $VERSION

      - name: Find MSI name
        id: grep_msi_name
        run: |
          FOR /F "tokens=*" %%g IN ('ls *.msi') do (SET msi_name=%%g)
          echo ::set-output name=msi_filename::%msi_name%
        # Otherwise it tries powershell
        shell: cmd

      - name: Download URL to upload to
        uses: actions/download-artifact@v2
        with:
          name: upload-url
        # Make it usable in Github actions
      - name: Set output for upload-url
        id: set_upload_url
        run: |
          FOR /F "tokens=*" %%g IN ('tail upload-url.txt') do (SET upload_url=%%g)
          echo ::set-output name=upload-url::%upload_url%
        # Otherwise it tries powershell
        shell: cmd

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.set_upload_url.outputs.upload-url }}
          asset_path: ${{ steps.grep_msi_name.outputs.msi_filename }}
          asset_name: FutureRestore-GUI-Windows-Continuous.msi
          asset_content_type: application/octet-stream

  publish-release:
    needs: [ ubuntu-pack, macos-pack, windows-pack ]
    runs-on: ubuntu-latest
    steps:
      - name: Download release ID
        uses: actions/download-artifact@v2
        with:
          name: release-id
      - name: Output release ID
        id: output-release-id
        run: |
          release_id=$(tail release-id.txt)
          echo "::set-output name=release-id::$release_id"

      - name: Publish release from draft
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.output-release-id.outputs.release-id }}